name: Daily Barrier-Chat Ingest

on:
  schedule:
    - cron: '0 5 * * *'   # Every day at 05:00 UTC
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch chat data (barriers-chat.json)
        run: |
          curl -s \
            -o barriers-chat.json \
            https://ctca2025.github.io/barrier-map-data/barriers-chat.json

      - name: Run ingest into Qdrant
        env:
          QDRANT_URL:     ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: python ingest.py

      - name: Sync chat JSON in repo (optional)
        run: |
          git config user.name  "github-actions"
          git config user.email "action@github.com"
          cp barriers-chat.json barriers-chat.json
          git add barriers-chat.json
          git commit -m "Sync chat data $(date +%F)" || echo "No changes"
          git push
